/**
 * Curated Cinematic Presets for GlobeLocation
 * Showcasing diverse templates, themes, and spectacular worldwide geography
 */

export const PRESETS = [
  {
    id: 'new-york-sky-zoom',
    name: 'New York City (Epic Space Zoom)',
    category: 'Globe to Place',
    template: 'globe-to-place',
    theme: 'satellite-cinematic',
    tagline: 'Manhattan, New York • 40.7128° N, 74.0060° W',
    description: 'Logarithmic dive from deep space orbit directly into Lower Manhattan & One World Trade Center with After Effects 3D tracked HUD badge, leader stalk, and atmospheric whoosh.',
    thumbnail: '🗽',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 8 },
    location: {
      name: 'New York City',
      description: 'Manhattan, United States • 40.7128° N, 74.0060° W',
      latitude: 40.7128,
      longitude: -74.0060,
      height: 480,
    },
    camera: {
      start: { longitude: -74.0060, latitude: 40.7128, height: 18500000, heading: 0, pitch: -88, roll: 0 },
      end: { longitude: -74.0105, latitude: 40.7056, height: 600, heading: 25, pitch: -34, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [],
    },
    overlays: [
      {
        id: 'pin-nyc',
        type: 'pin',
        latitude: 40.7128,
        longitude: -74.0060,
        height: 10,
        label: 'NEW YORK CITY',
        sublabel: 'Manhattan, United States',
        color: '#f59e0b',
        icon: 'location_on',
        pulse: true,
        stalkHeight: 140,
      },
    ],
    timeline: [
      { id: 't1', at: 4.6, action: 'showTitle', text: 'NEW YORK CITY', subtext: '40.7128° N, 74.0060° W • Lower Manhattan', position: 'lower-third' },
    ],
  },
  {
    id: 'dubai-burj-zoom',
    name: 'Dubai (Stratosphere Dive)',
    category: 'Globe to Place',
    template: 'globe-to-place',
    theme: 'satellite-cinematic',
    tagline: 'Downtown Dubai & Burj Khalifa • 25.1972° N, 55.2744° E',
    description: 'Hypersonic descent from global satellite view into Downtown Dubai and the spire of Burj Khalifa with glowing cyan HUD badge.',
    thumbnail: '🏙️',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 8 },
    location: {
      name: 'Dubai, UAE',
      description: 'Downtown Dubai • 25.1972° N, 55.2744° E',
      latitude: 25.1972,
      longitude: 55.2744,
      height: 850,
    },
    camera: {
      start: { longitude: 55.2744, latitude: 25.1972, height: 16500000, heading: 0, pitch: -88, roll: 0 },
      end: { longitude: 55.2656, latitude: 25.1892, height: 850, heading: 45, pitch: -34, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [],
    },
    overlays: [
      {
        id: 'pin-dubai',
        type: 'pin',
        latitude: 25.1972,
        longitude: 55.2744,
        height: 15,
        label: 'BURJ KHALIFA',
        sublabel: 'Downtown Dubai, UAE',
        color: '#06b6d4',
        icon: 'location_on',
        pulse: true,
        stalkHeight: 280,
      },
    ],
    timeline: [
      { id: 't1', at: 4.5, action: 'showTitle', text: 'BURJ KHALIFA & DUBAI', subtext: '25.1972° N, 55.2744° E • Spire Elevation 828m', position: 'lower-third' },
    ],
  },
  {
    id: 'everest-expedition',
    name: 'Mount Everest Expedition',
    category: 'Route Flyover',
    template: 'route-flyover',
    theme: 'documentary',
    tagline: 'Nepal / Tibet Border • 8,848m',
    description: 'Fly along the legendary South Col route from Everest Base Camp past the Khumbu Icefall to the highest point on Earth.',
    thumbnail: '🏔️',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 12 },
    location: {
      name: 'Mount Everest',
      description: 'Khumbu Region, Himalayas, Nepal',
      latitude: 27.9881,
      longitude: 86.9250,
      height: 9800,
    },
    camera: {
      start: { longitude: 86.852, latitude: 27.995, height: 7500, heading: 95, pitch: -20, roll: 0 },
      end: { longitude: 86.925, latitude: 27.988, height: 9600, heading: 110, pitch: -30, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [
        { longitude: 86.852, latitude: 27.995, height: 6000, name: 'Base Camp (5,364m)' },
        { longitude: 86.885, latitude: 27.988, height: 7200, name: 'Camp II & Lhotse Face' },
        { longitude: 86.918, latitude: 27.980, height: 8300, name: 'South Col (7,906m)' },
        { longitude: 86.925, latitude: 27.988, height: 9600, name: 'Everest Summit (8,848m)' },
      ],
    },
    overlays: [
      {
        id: 'pin-everest',
        type: 'pin',
        latitude: 27.9881,
        longitude: 86.9250,
        height: 8848,
        label: 'Mt. Everest Summit',
        sublabel: '8,848 m / 29,032 ft',
        color: '#f59e0b',
        icon: 'terrain',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 1.5, action: 'showTitle', text: 'Mount Everest Expedition', subtext: 'Ascent to the Roof of the World', position: 'lower-third' },
      { id: 't2', at: 8.0, action: 'showTitle', text: 'Khumbu Ridge & Summit', subtext: 'Elevation 8,848m', position: 'center' },
    ],
  },
  {
    id: 'tokyo-night-reveal',
    name: 'Tokyo Neon Metropolis',
    category: 'Place Reveal',
    template: 'place-reveal',
    theme: 'dark-data',
    tagline: 'Tokyo, Japan • Shibuya & Skytree',
    description: 'An aerial 360-degree orbit reveal over Tokyo, transitioning between Shibuya Crossing and the illuminated Skytree.',
    thumbnail: '🗼',
    format: { aspectRatio: '9:16', width: 1080, height: 1920, fps: 30, durationSeconds: 8 },
    location: {
      name: 'Tokyo, Japan',
      description: 'Kanto Region • Metropolitan Metropolis',
      latitude: 35.6895,
      longitude: 139.6917,
      height: 1800,
    },
    camera: {
      start: { longitude: 139.6917, latitude: 35.6895, height: 3200, heading: -45, pitch: -30, roll: 0 },
      end: { longitude: 139.7500, latitude: 35.6762, height: 1600, heading: 45, pitch: -38, roll: 0 },
      easing: 'cubicInOut',
      orbitAngle: 90,
      waypoints: [],
    },
    overlays: [
      {
        id: 'pin-tokyo',
        type: 'pin',
        latitude: 35.6895,
        longitude: 139.6917,
        height: 0,
        label: 'Tokyo City Center',
        sublabel: 'Greater Tokyo Area (37M residents)',
        color: '#06b6d4',
        icon: 'apartment',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 3.5, action: 'showTitle', text: 'Tokyo Metropolis', subtext: 'The World’s Largest Megacity', position: 'lower-third' },
    ],
  },
  {
    id: 'sf-bay-story',
    name: 'San Francisco Tech Corridor',
    category: 'Multi-Stop Story',
    template: 'multi-stop',
    theme: 'documentary',
    tagline: 'California, USA • Golden Gate to Bay',
    description: 'A cinematic multi-chapter sequence connecting the Golden Gate Bridge, downtown Salesforce Tower, and Silicon Valley.',
    thumbnail: '🌉',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 14 },
    location: {
      name: 'San Francisco Bay Area',
      description: 'Northern California, USA',
      latitude: 37.8199,
      longitude: -122.4783,
      height: 1500,
    },
    camera: {
      start: { longitude: -122.52, latitude: 37.83, height: 2800, heading: 110, pitch: -25, roll: 0 },
      end: { longitude: -122.39, latitude: 37.78, height: 1400, heading: 40, pitch: -35, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [
        { longitude: -122.4783, latitude: 37.8199, height: 1500, name: 'Chapter 1: Golden Gate Bridge' },
        { longitude: -122.4000, latitude: 37.7950, height: 1200, name: 'Chapter 2: Financial District & Salesforce Tower' },
        { longitude: -122.3850, latitude: 37.7700, height: 1800, name: 'Chapter 3: Mission Bay & Biotech Hub' },
      ],
    },
    overlays: [
      {
        id: 'pin-ggb',
        type: 'pin',
        latitude: 37.8199,
        longitude: -122.4783,
        height: 227,
        label: 'Golden Gate Bridge',
        sublabel: 'Opened 1937 • 2.7 km span',
        color: '#ef4444',
        icon: 'bridge',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 1.0, action: 'showTitle', text: 'San Francisco, California', subtext: 'Innovation Hub of the Pacific Rim', position: 'lower-third' },
      { id: 't2', at: 7.0, action: 'showTitle', text: 'Downtown & Financial District', subtext: 'Market Street Corridor', position: 'lower-third' },
    ],
  },
  {
    id: 'giza-globe-reveal',
    name: 'Pyramids of Giza Descent',
    category: 'Globe to Place',
    template: 'globe-to-place',
    theme: 'satellite-cinematic',
    tagline: 'Cairo, Egypt • 4,500 Years of History',
    description: 'Start from low Earth orbit over the Sahara Desert and dive dramatically right into the Great Pyramid of Giza and the Nile.',
    thumbnail: '🏺',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 9 },
    location: {
      name: 'Great Pyramids of Giza',
      description: 'Al Giza Desert, Cairo, Egypt',
      latitude: 29.9792,
      longitude: 31.1342,
      height: 1800,
    },
    camera: {
      start: { longitude: 28.0, latitude: 24.0, height: 16000000, heading: 25, pitch: -85, roll: 0 },
      end: { longitude: 31.1342, latitude: 29.9792, height: 1600, heading: 45, pitch: -36, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [],
    },
    overlays: [
      {
        id: 'pin-giza',
        type: 'pin',
        latitude: 29.9792,
        longitude: 31.1342,
        height: 140,
        label: 'Great Pyramid of Khufu',
        sublabel: 'c. 2560 BCE • Last Ancient Wonder',
        color: '#f59e0b',
        icon: 'castle',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 5.5, action: 'showTitle', text: 'The Pyramids of Giza', subtext: 'Monumental Heritage of Ancient Egypt', position: 'lower-third' },
    ],
  },
  {
    id: 'paris-seine-flyover',
    name: 'Paris & The River Seine',
    category: 'Route Flyover',
    template: 'route-flyover',
    theme: 'documentary',
    tagline: 'Paris, France • Eiffel Tower to Louvre',
    description: 'Low-altitude drone sweep following the winding curves of the Seine river through the historic center of Paris.',
    thumbnail: '🥐',
    format: { aspectRatio: '9:16', width: 1080, height: 1920, fps: 30, durationSeconds: 10 },
    location: {
      name: 'Paris, France',
      description: 'Île-de-France',
      latitude: 48.8584,
      longitude: 2.2945,
      height: 1200,
    },
    camera: {
      start: { longitude: 2.3522, latitude: 48.8530, height: 1800, heading: 260, pitch: -28, roll: 0 },
      end: { longitude: 2.2945, latitude: 48.8584, height: 1100, heading: 295, pitch: -32, roll: 0 },
      easing: 'cubicInOut',
      waypoints: [
        { longitude: 2.3522, latitude: 48.8530, height: 1500, name: 'Notre-Dame Cathedral' },
        { longitude: 2.3376, latitude: 48.8606, height: 1300, name: 'Louvre Museum' },
        { longitude: 2.2945, latitude: 48.8584, height: 1100, name: 'Eiffel Tower' },
      ],
    },
    overlays: [
      {
        id: 'pin-eiffel',
        type: 'pin',
        latitude: 48.8584,
        longitude: 2.2945,
        height: 300,
        label: 'Eiffel Tower',
        sublabel: 'Paris 7th Arrondissement',
        color: '#06b6d4',
        icon: 'tower',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 1.0, action: 'showTitle', text: 'Paris, France', subtext: 'Along the River Seine', position: 'top-banner' },
      { id: 't2', at: 6.5, action: 'showTitle', text: 'Eiffel Tower', subtext: 'Champ de Mars', position: 'lower-third' },
    ],
  },
  {
    id: 'grand-canyon-rim',
    name: 'Grand Canyon Majesty',
    category: 'Place Reveal',
    theme: 'satellite-cinematic',
    template: 'place-reveal',
    tagline: 'Arizona, USA • Colorado River Basin',
    description: 'Dramatic descent into the stratified rock gorges of the Grand Canyon South Rim at golden hour.',
    thumbnail: '🏜️',
    format: { aspectRatio: '16:9', width: 1920, height: 1080, fps: 30, durationSeconds: 8 },
    location: {
      name: 'Grand Canyon South Rim',
      description: 'Arizona, United States',
      latitude: 36.0544,
      longitude: -112.1401,
      height: 3400,
    },
    camera: {
      start: { longitude: -112.20, latitude: 36.02, height: 5500, heading: 45, pitch: -22, roll: 0 },
      end: { longitude: -112.14, latitude: 36.06, height: 3200, heading: 85, pitch: -36, roll: 0 },
      easing: 'cubicInOut',
      orbitAngle: 60,
      waypoints: [],
    },
    overlays: [
      {
        id: 'pin-canyon',
        type: 'pin',
        latitude: 36.0544,
        longitude: -112.1401,
        height: 2100,
        label: 'Mather Point Overlook',
        sublabel: 'Elevation 2,170m • South Rim',
        color: '#f59e0b',
        icon: 'landscape',
        pulse: true,
      },
    ],
    timeline: [
      { id: 't1', at: 3.5, action: 'showTitle', text: 'Grand Canyon National Park', subtext: 'Two Billion Years of Earth’s Geological History', position: 'lower-third' },
    ],
  },
];
